services:
    rogai-backend:
        build: .
        ports:
            - 8082:8080
        networks:
            - db_to_backend
        depends_on:
            rogai-db:
                condition: service_healthy
        command: /bin/sh -c /app/start.sh
        environment:
            DB_HOST: rogai-db
            APP_URL: "http://localhost:8082"
        restart: always
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 1G

    rogai-db:
        image: mariadb:12.2.2
        restart: always
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 512M
        networks:
            - db_to_backend
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_PORT: ${DB_PORT}
        volumes:
            - db_volume_data:/var/lib/mariadb
        healthcheck:
            test:
                [
                    "CMD",
                    "mariadb-admin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p${DB_PASSWORD}",
                ]
            timeout: 5s
            retries: 5

networks:
    db_to_backend:
        driver: bridge

volumes:
    db_volume_data:
