services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - ../..:/workspaces:cached
        ports:
            - "8000:8000"
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity

        # Allows "forwardPorts" in devcontainer.json function.

        # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)

    db:
        image: mariadb:10.4
        restart: unless-stopped
        volumes:
            - mariadb-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rogaiconosco
            MYSQL_DATABASE: rogaiconosco
            MYSQL_USER: rogaiconosco
            MYSQL_PASSWORD: rogaiconosco

        # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
    mariadb-data:
